#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4F398DEAE440091C (infra-root@openstack.org)
#
Name     : python-barbicanclient
Version  : 4.10.0
Release  : 44
URL      : http://tarballs.openstack.org/python-barbicanclient/python-barbicanclient-4.10.0.tar.gz
Source0  : http://tarballs.openstack.org/python-barbicanclient/python-barbicanclient-4.10.0.tar.gz
Source1  : http://tarballs.openstack.org/python-barbicanclient/python-barbicanclient-4.10.0.tar.gz.asc
Summary  : Client library for the Barbican Key Management API
Group    : Development/Tools
License  : Apache-2.0
Requires: python-barbicanclient-bin = %{version}-%{release}
Requires: python-barbicanclient-license = %{version}-%{release}
Requires: python-barbicanclient-python = %{version}-%{release}
Requires: python-barbicanclient-python3 = %{version}-%{release}
Requires: cliff
Requires: keystoneauth1
Requires: oslo.i18n
Requires: oslo.serialization
Requires: oslo.utils
Requires: pbr
Requires: requests
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : cliff
BuildRequires : keystoneauth1
BuildRequires : oslo.i18n
BuildRequires : oslo.serialization
BuildRequires : oslo.utils
BuildRequires : pbr
BuildRequires : requests
BuildRequires : six

%description
python-barbicanclient
=====================
.. image:: https://img.shields.io/pypi/v/python-barbicanclient.svg
:target: https://pypi.org/project/python-barbicanclient/
:alt: Latest Version

%package bin
Summary: bin components for the python-barbicanclient package.
Group: Binaries
Requires: python-barbicanclient-license = %{version}-%{release}

%description bin
bin components for the python-barbicanclient package.


%package license
Summary: license components for the python-barbicanclient package.
Group: Default

%description license
license components for the python-barbicanclient package.


%package python
Summary: python components for the python-barbicanclient package.
Group: Default
Requires: python-barbicanclient-python3 = %{version}-%{release}

%description python
python components for the python-barbicanclient package.


%package python3
Summary: python3 components for the python-barbicanclient package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-barbicanclient package.


%prep
%setup -q -n python-barbicanclient-4.10.0
cd %{_builddir}/python-barbicanclient-4.10.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1581608549
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-barbicanclient
cp %{_builddir}/python-barbicanclient-4.10.0/LICENSE %{buildroot}/usr/share/package-licenses/python-barbicanclient/c28c411a3f03448bfafa39be7e98d0fef9dd7070
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/barbican

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-barbicanclient/c28c411a3f03448bfafa39be7e98d0fef9dd7070

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
